apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: customer
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 6
  configs:
    cleanup.policy: "delete"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: confluent
data:
  client-config.properties: |
    bootstrap.servers=kafka.confluent.svc.cluster.local:9092
    security.protocol=SSL
    ssl.truststore.type=PEM
    ssl.truststore.location=/etc/ssl/certs/ca.crt
    ssl.keystore.type=PEM
    ssl.keystore.location=/etc/ssl/client-keys/tls-keypair.pem
    ssl.key.password=changeme
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-client
  labels:
    app: kafka-client
spec:
  clusterIP: None
  selector:
    app: kafka-client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-client
  namespace: confluent
spec:
  serviceName: kafka-client
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      initContainers:
        - name: convert-pkcs1-to-pkcs8
          image: alpine/openssl
          command:
            - sh
            - -c
            - |
              openssl pkcs8 -topk8 -inform PEM -outform pem -in /etc/ssl/client-certs/tls.key -outform pem -out /config/tls-pkcs8.key -passout pass:changeme
              cat /config/tls-pkcs8.key /etc/ssl/client-certs/tls.crt > /config/tls-keypair.pem
              chmod 644 /config/tls-pkcs8.key /config/tls-keypair.pem
          volumeMounts:
            - mountPath: /etc/ssl/client-certs
              name: client-cert-volume
            - mountPath: /config
              name: client-key-volume
      containers:
        - name: kafka-client
          image: confluentinc/cp-kafka:latest
          volumeMounts:
            - name: cert-volume
              mountPath: /etc/ssl/certs  # Directory inside the container
              readOnly: true
            - name: config-volume
              mountPath: /etc/kafka-client/config/client-config.properties
              subPath: client-config.properties
              readOnly: true
            - name: client-cert-volume
              mountPath: /etc/ssl/client-certs
              readOnly: true
            - name: client-key-volume
              mountPath: /etc/ssl/client-keys
              readOnly: true
          command:
            - /bin/sh
            - -c
            - |
               sleep infinity
      resources:
        requests:
          memory: 512Mi # 768Mi
          cpu: 500m # 1000m
      volumes:
        - name: cert-volume
          secret:
            secretName: root-secret
        - name: config-volume
          configMap:
            name: client-config
        - name: client-key-volume
          emptyDir: {}
        - name: client-cert-volume
          secret:
            secretName: producer-tls



---
# Connect to kafka.confluent.svc.cluster.local:9092
# Test with kafka-topics --list --bootstrap-server kafka.confluent.svc.cluster.local:9092 --command-config client-config.properties
