apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: KRaftController
      name: kraftcontroller
    patch: |-
      - op: add
        path: /spec/tls
        value: { secretRef: kraft-tls }
      - op: add
        path: /spec/listeners
        value:
          controller:
            tls: { enabled: true }
  - target:
      kind: Kafka
      name: kafka
    patch: |-
      - op: add
        path: /spec/tls
        value: { secretRef: kafka-tls }
      - op: add
        path: /spec/listeners
        value:
          internal:
            tls: { enabled: true }
          external:
            tls: { enabled: true }
      - op: add
        path: /spec/dependencies/kRaftController/controllerListener
        value: { tls: { enabled: true } }

  - target:
      kind: ControlCenter
      name: controlcenter
    patch: |-
      - op: add
        path: /spec/tls
        value: { secretRef: controlcenter-tls }
      - op: add
        path: /spec/dependencies/kafka/tls
        value: { enabled: true }
      - op: replace
        path: /spec/dependencies/schemaRegistry/url
        value: "https://schemaregistry.confluent.svc.cluster.local:8081"
      - op: add
        path: /spec/dependencies/schemaRegistry/tls
        value: { enabled: true }
      - op: replace
        path: /spec/dependencies/ksqldb/0/url
        value: "https://ksqldb.confluent.svc.cluster.local:8088"
      - op: add
        path: /spec/dependencies/ksqldb/0/tls
        value: { enabled: true }
      - op: replace
        path: /spec/dependencies/connect/0/url
        value: "https://connect.confluent.svc.cluster.local:8083"
      - op: add
        path: /spec/dependencies/connect/0/tls
        value: { enabled: true }

  - target:
      kind: SchemaRegistry
      name: schemaregistry
    patch: |-
      - op: add
        path: /spec/tls
        value: { secretRef: schemaregistry-tls }
      - op: add
        path: /spec/dependencies/kafka/tls
        value: { enabled: true }

  - target:
      kind: Connect
      name: connect
    patch: |-
      - op: add
        path: /spec/tls
        value: { secretRef: connect-tls }
      - op: add
        path: /spec/dependencies/kafka/tls
        value: { enabled: true }

  - target:
      kind: KsqlDB
      name: ksqldb
    patch: |-
      - op: add
        path: /spec/tls
        value: { secretRef: ksqldb-tls }
      - op: add
        path: /spec/dependencies/kafka/tls
        value: { enabled: true }

  - target:
      kind: KafkaRestProxy
      name: kafkarestproxy
    patch: |-
      - op: add
        path: /spec/tls
        value: { secretRef: kafkarestproxy-tls }
      - op: add
        path: /spec/dependencies/kafka/tls
        value: { enabled: true }

