apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: KRaftController
      name: kraftcontroller
    patch: |-
      - op: add
        path: /spec/license
        value: { globalLicense: true }

  - target:
      kind: Kafka
      name: kafka
    patch: |-
      - op: add
        path: /spec/license
        value: { globalLicense: true }

  - target:
      kind: ControlCenter
      name: controlcenter
    patch: |-
      - op: add
        path: /spec/license
        value: { globalLicense: true }

  - target:
      kind: SchemaRegistry
      name: schemaregistry
    patch: |-
      - op: add
        path: /spec/license
        value: { globalLicense: true }

  - target:
      kind: Connect
      name: connect
    patch: |-
      - op: add
        path: /spec/license
        value: { globalLicense: true }

  - target:
      kind: KsqlDB
      name: ksqldb
    patch: |-
      - op: add
        path: /spec/license
        value: { globalLicense: true }

  - target:
      kind: KafkaRestProxy
      name: kafkarestproxy
    patch: |-
      - op: add
        path: /spec/license
        value: { globalLicense: true }

