# nonk8s
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 9093
        hostPort: 9093
        protocol: TCP
      - containerPort: 9094
        hostPort: 9094
        protocol: TCP
      - containerPort: 9095
        hostPort: 9095
        protocol: TCP
