apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

components:
  - ../../../components/tls
  - ../../../components/cmf
  - ../../../components/sasl_plain

images:
  - name: confluentinc/confluent-init-container
    newTag: 3.1.1
  - name: confluentinc/cp-server
    newTag: 8.1.1
  - name: confluentinc/cp-server-connect
    newTag: 8.1.1
  - name: confluentinc/cp-ksqldb-server
    newTag: 8.1.1
  - name: confluentinc/cp-schema-registry
    newTag: 8.1.1
  - name: confluentinc/cp-kafka-rest
    newTag: 8.1.1
  - name: confluentinc/cp-enterprise-control-center-next-gen
    newTag: 2.4.0
  - name: confluentinc/cp-enterprise-prometheus
    newTag: 2.4.0
  - name: confluentinc/cp-enterprise-alertmanager
    newTag: 2.4.0
