apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Kafka
      name: kafka
    patch: |-
      - op: add
        path: /spec/listeners
        value: 
          external:
            externalAccess:
              type: loadBalancer
              loadBalancer:
                domain: bootcamp.confluent.io
