apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Kafka
      name: kafka
    patch: |-
      apiVersion: platform.confluent.io/v1beta1
      kind: Kafka
      metadata:
        name: kafka
      spec:
        listeners:
          external:
            externalAccess:
              type: loadBalancer
              loadBalancer:
                domain: bootcamp.confluent.io
  - target:
      kind: SchemaRegistry
      name: schemaregistry
    patch: |-
      apiVersion: platform.confluent.io/v1beta1
      kind: SchemaRegistry
      metadata:
        name: schemaregistry
      spec:
          externalAccess:
            type: loadBalancer
            loadBalancer:
              domain: bootcamp.confluent.io
#                annotations:
#                  # 🎯 The magic annotation for your script
#                  external-dns.alpha.kubernetes.io/hostname: "sr.bootcamp.confluent.io"
  - target:
      kind: Connect
      name: connect
    patch: |-
      apiVersion: platform.confluent.io/v1beta1
      kind: Connect
      metadata:
        name: connect
      spec:
          externalAccess:
            type: loadBalancer
            loadBalancer:
              domain: bootcamp.confluent.io

