apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: KRaftController
      name: kraftcontroller
    patch: |-
      - op: add
        path: /spec/podTemplate
        value:
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"

  - target:
      kind: Kafka
      name: kafka
    patch: |-
      - op: add
        path: /spec/podTemplate
        value:
          resources:
            requests:
              cpu: "4"
              memory: "16Gi"
            limits:
              cpu: "8"
              memory: "32Gi"

  - target:
      kind: ControlCenter
      name: controlcenter
    patch: |-
      - op: add
        path: /spec/podTemplate
        value:
          resources:
            requests:
              cpu: "4"
              memory: "16Gi"
            limits:
              cpu: "8"
              memory: "32Gi"

  - target:
      kind: SchemaRegistry
      name: schemaregistry
    patch: |-
      - op: add
        path: /spec/podTemplate
        value:
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"

  - target:
      kind: Connect
      name: connect
    patch: |-
      - op: add
        path: /spec/podTemplate
        value:
          resources:
            requests:
              cpu: "4"
              memory: "16Gi"
            limits:
              cpu: "8"
              memory: "32Gi"

  - target:
      kind: KsqlDB
      name: ksqldb
    patch: |-
      - op: add
        path: /spec/podTemplate
        value:
          resources:
            requests:
              cpu: "4"
              memory: "16Gi"
            limits:
              cpu: "8"
              memory: "32Gi"

  - target:
      kind: KafkaRestProxy
      name: kafkarestproxy
    patch: |-
      - op: add
        path: /spec/podTemplate
        value:
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"

